version: "3"

services:

  database:

    # Build the image using this directory as the context.
    build:
      context: ./database

    # Set the image to run.
    image: database

    # Use lower-case table names.
    command:
      --lower_case_table_names=1
    
    # Set default mysql root password.
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "3306:3306"
    
    # Restart on failure, up to max-retries attempts.
    restart: on-failure:10

    # Nicer container name.
    container_name: MysqlContainer

  webserver:

    # Build the image using this directory as the context.
    build: 
      context: ./webserver

    # Set the image to run.
    image: webserver
    
    # Open ports for Tomcat home, remote debugging.
    ports:
      - "8080:8080"
      - "8000:8000"

    # Restart on failure, up to max-retries attempts.
    restart: on-failure:10

    # Nicer container name.
    container_name: TomcatContainer
